// Comprehensive name mappings for C&C edition changes
// Generated from the CnC Name Changes spreadsheets

// Spell name mappings (Original → New Name)
export const SPELL_NAME_MAPPINGS: Record<string, string> = {
  'acid arrow': 'Acidic Bolt',
  'air/water walk': 'Air/Water Stride',
  'alter self': 'Alter One\'s Person Greater',
  'alter size': 'Alter Size',
  'animal friendship': 'Animal Bond',
  'animal growth': 'Animal Alteration',
  'animal messenger': 'Animal Courier',
  'animal shapes': 'Animal Form',
  'animate dead': 'Animate Corpse',
  'anti-illusion shield': 'Anti Illusion Sphere',
  'anti-life shell': 'Anti Life Sphere',
  'anti-magic shell': 'Anti Magic Sphere',
  'anti-plant shell': 'Anti Plant Sphere',
  'arcane eye': 'Arcane Vision',
  'arcane mark': 'Arcane Rune',
  'astral projection': 'Astral Travel',
  'banishment': 'Banishment',
  'barkskin': 'Barkform',
  'binding': 'Bind',
  'blade barrier': 'Blade Blockade',
  'bless': 'Bless',
  'bless water': 'Blessing Water',
  'burning hands': 'Burning Flames',
  'call lightning': 'Conjure Lightning',
  'calm animals': 'Calm Animals',
  'change self': 'Alter One\'s Person Lesser',
  'changestaff': 'Change Stave to Treant',
  'charm person': 'Charm Humanoid',
  'charm person or animal': 'Charm Humanoid or Animal',
  'cloak of dark chaos': 'Cloak of Smoke and Darkness',
  'cloudkill': 'Cloud of Pestilence',
  'color spray': 'Colors',
  'command plants': 'Command Plants',
  'commune': 'Commune',
  'commune with nature': 'Commune with the Natural World',
  'comprehend languages': 'Comprehension',
  'cone of cold': 'Cone of Winter\'s Blast',
  'consecrate': 'Consecrate',
  'contact other plane': 'Contact Other Worlds',
  'continual flame': 'Continual Fire',
  'control plants': 'Control Plants',
  'control water': 'Control Liquids',
  'control weather': 'Control Atmosphere',
  'control winds': 'Control Gales',
  'create food and water': 'Create Sustenance',
  'create greater undead': 'Create Common & Extraordinary Undead',
  'create undead': 'Create Unique Undead',
  'create water': 'Create Water',
  'creeping doom': 'Creeping Swarm',
  'cure light wounds': 'Heal Light Wounds',
  'cure critical wounds': 'Heal Critical Wounds',
  'cure serious wounds': 'Heal Serious Wounds',
  'dancing lights': 'Dancing Orbs',
  'dark chaos': 'Dark Whips',
  'darkness': 'Darkness',
  'death ward': 'Death Mask',
  'delay poison': 'Delay Toxin',
  'delayed blast fireball': 'Delayed Fireball',
  'detect alignment': 'Detect Disposition',
  'detect illusion': 'Discern Illusion',
  'detect magic': 'Discern Magic',
  'detect neutrality': 'Detect Disposition',
  'detect poison': 'Discover Poison',
  'detect scrying': 'Discern Scrying',
  'detect secret doors': 'Discover Secret Doors',
  'detect snares and pits': 'Discover Snares and Pits',
  'detect thoughts': 'Discern Thoughts',
  'detect traps': 'Discover Traps',
  'detect undead': 'Discover Undead',
  'dimension door': 'Dimensional Leap',
  'discern lies': 'Discern Falsehood',
  'discern location': 'Discover Location',
  'dispel alignment': 'Dispel Disposition',
  'displaced image': 'Displace',
  'distort reality': 'Distort Reality',
  'double treasure': 'Doubled Treasure',
  'endure elements': 'Endure Cold/Heat',
  'energy drain': 'Energy Level Drain',
  'enhance attribute': 'Enhance an Attribute',
  'entangle': 'Entangling Vegetation',
  'ethereal jaunt': 'Ethereal Jump',
  'explosive runes': 'Explosive Mark',
  'eyes of fire': 'Eyes of Chaos',
  'faerie fire': 'Faerie Aura',
  'faeries glamour': 'Faerie Reflection',
  'faithful hound': 'Faithful Watchdog',
  'false trap': 'False Snare or Trap',
  'false vision': 'False Scrying',
  'feather fall': 'Feather Light',
  'find the path': 'Finding Trails',
  'finger of death': 'Fatal Gesture',
  'fireball': 'Fireballs',
  'fire seeds': 'Flame Seeds',
  'fire shield': 'Flame Shield',
  'fire storm': 'Flaming Tempest',
  'fire trap': 'Flame Snare',
  'flame strike': 'Flame of the Divine',
  'floating disc': 'Flying Saucer',
  'fog cloud': 'Fog',
  'freedom of movement': 'Free Motion',
  'gaseous form': 'Gas Form',
  'ghost sound': 'Ghostly Noise',
  'globe of invulnerability': 'Globe of Spell Protection',
  'glyph of warding': 'Glyphs',
  'goodberry': 'Good Fruit',
  'greater restoration': 'Restoration',
  'greater scrying': 'Scrying',
  'greater shadow conjuration': 'Conjure Phantasm',
  'greater shadow evocation': 'Evoke Arcane Phantasm',
  'guards and wards': 'Guard with Wards',
  'gust of wind': 'Gust',
  'hallow': 'Hallow',
  'hallucinatory terrain': 'Hallucinatory Ground',
  'haste': 'Haste',
  'heal': 'Heal',
  'healing circle': 'Healing Sphere',
  'heat metal': 'Heat any Alloy',
  'hold animal': 'Hold Animals and Plants',
  'hold monster': 'Hold Creature',
  'hold person': 'Hold Humanoid',
  'hold portal': 'Hold & Bar Gate',
  'holy aura': 'Holy Glamour',
  'holy word': 'Holy Utterance',
  'humanoid finding': 'Humanoid Finding',
  'hypnotic pattern': 'Hypnotic Imagery',
  'hypnotism': 'Hypnotism',
  'ice storm': 'Ice Storm',
  'illusionary help': 'Illusionary Help',
  'illusory hounds': 'Illusionary Hounds',
  'illusionary lions': 'Illusionary Lions',
  'illusory script': 'Illusory Writing',
  'illusory wall': 'Illusory Barrier',
  'imprisonment': 'Imprison',
  'improved invisibility': 'Invisibility Heightened',
  'incendiary cloud': 'Incendiary Flow',
  'insect plague': 'Insect Swarm',
  'instant summons': 'Instant Item',
  'invisible': 'Invisibility',
  'invisibility sphere': 'Invisibility Orb',
  'invisibility to animals': 'Invisibility to Animals',
  'invisibility to undead': 'Invisible Cloak of the Undead',
  'ironwood': 'Ironbark',
  'know direction': 'Know the Path',
  'legend lore': 'Legendary Tales',
  'lesser restoration': 'Restoration',
  'lightning bolt': 'Lightning',
  'limited wish': 'Wish, Minor',
  'locate creature': 'Locate Other',
  'locate object': 'Locate Item',
  'mage hand': 'Magi\'s Reach',
  'magic aura': 'Magi\'s Glamour',
  'magic jar': 'Magi\'s Vessel',
  'magic missile': 'Magi\'s Missile',
  'magic mouth': 'Magi\'s Visage',
  'magic stones': 'Magic Sling',
  'major creation': 'Magi\'s Conjuring',
  'major dark chaos': 'Major Dark Whips',
  'major image': 'Illusion',
  'mass charm': 'Charm Area',
  'mass heal': 'Heal in Area',
  'mass invisibility': 'Invisibility in Area',
  'mass suggestion': 'Suggestion in Area',
  'meld into stone': 'Meld',
  'mending': 'Mending',
  'meteor swarm': 'Meteor Shower',
  'mind blank': 'Mind Ward',
  'minor dark chaos': 'Minor Dark Whips',
  'minor creation': 'Minor Concoction',
  'minor globe of invulnerability': 'Minor Globe of Spell Protection',
  'minor image': 'Illusion',
  'mirage arcana': 'Mirage',
  'mirror image': 'Mirrored Self',
  'mislead': 'Misguide',
  'mnemonic enhancer': 'Mnemonic Enhancement',
  'move earth': 'Harrow the Earth',
  'neutralize poison': 'Neutralize Toxins',
  'nondetection': 'Nondetection',
  'obscuring mist': 'Obscure with Mist',
  'open/close': 'Open/Close',
  'passwall': 'Passage',
  'pass without trace': 'Pass with Woodland Stride',
  'permanent image': 'Perpetual Illusion',
  'persistent image': 'Persevering Illusion',
  'phantasmal killer': 'Phantasm',
  'phase door': 'Phase through Obstruction',
  'plane shift': 'Planar Travel',
  'plant growth': 'Plant Growth',
  'polymorph any object': 'Polymorph Creatures & Things',
  'polymorph other': 'Polymorph Creature',
  'polymorph self': 'Polymorph Own Person',
  'power word blind': 'Power of the Spoken Word: Purblind',
  'power word kill': 'Power of the Spoken Word: Slay',
  'power word stun': 'Power of the Spoken Word: Immobilize',
  'prismatic sphere': 'Polychromatic Sphere',
  'prismatic spray': 'Polychromatic Spray',
  'prismatic wall': 'Polychromatic Wall',
  'produce flame': 'Produce Fire',
  'programmed image': 'Programmed Illusion',
  'project image': 'Projection',
  'protection from alignment': 'Protection from Disposition',
  'protection from arrows': 'Protection from Normal Missiles',
  'protection from elements': 'Protection from Elemental Attacks',
  'purify food and drink': 'Purify',
  'rainbow pattern': 'Rainbow',
  'raise dead': 'Raise',
  'ray of enfeeblement': 'Ray of Weakening',
  'read magic': 'Read Arcane Script',
  'remove blindness or deafness': 'Restore Sight & Hearing',
  'remove curse': 'Remove Bane',
  'remove disease': 'Remove Malady',
  'remove fear': 'Remove Despair',
  'remove paralysis': 'Restore Movement',
  'repel metal or stone': 'Remove Alloy and Stone from Path',
  'repel vermin': 'Repel Pest',
  'repel wood': 'Remove Wood from Path',
  'resilient sphere': 'Resilient Globe',
  'resist elements': 'Resist One Element',
  'restoration': 'Restoration',
  'rope trick': 'Rope Dimension',
  'secret chest': 'Secret Container',
  'secret page': 'Secret Script',
  'secure shelter': 'Shelter',
  'see invisibility': 'See Invisible',
  'seeming': 'Seeming',
  'sending': 'Send',
  'shades': 'Shades',
  'shadow conjuration': 'Shadow Convocation',
  'shadow evocation': 'Shadow Sorcery',
  'shadow walk': 'Shadow Journey',
  'shapechange': 'Shapeshift',
  'shape stone or wood': 'Shape Stone or Wood',
  'shield of faith': 'Shield of the Divine',
  'shocking grasp': 'Shock',
  'silent image': 'Silent Illusion',
  'sleet storm': 'Sleet',
  'solid fog': 'Solidlike Fog',
  'soul bind': 'Soul to Gem',
  'sound burst': 'Sound Storm',
  'speak with animals': 'Speak with Animals',
  'speak with dead': 'Speak with the Dead',
  'speak with plants': 'Speak with Plants',
  'spider climb': 'Spider Walk',
  'spike stones': 'Spike Spell',
  'spiritual weapon': 'Spiritual Warrior',
  'stinking cloud': 'Stench',
  'stone tell': 'Stone Speak',
  'storm of vengeance': 'Storm of Wrath',
  'summon animal': 'Summon Animals',
  'summon beasts or plants': 'Summon Beasts and Plants',
  'summon elemental': 'Summon Elemental Being',
  'summon elemental swarm': 'Summon Elemental Horde',
  'summon familiar': 'Summon Familiar',
  'summon greater monster': 'Summon Monstrous Ally',
  'summon lesser monster': 'Summon Monstrous Ally',
  'summon magical beast or fey': 'Summon Fey and Magical Beasts',
  'summon monster': 'Summon Monstrous Ally',
  'summon planar ally': 'Summon Extraplanary Ally',
  'summon swarm': 'Summon Pests',
  'sunburst': 'Sun Flare',
  'telepathic bond': 'Telepathy',
  'teleport': 'Teleportation',
  'teleportation circle': 'Teleportation Field',
  'teleport without error': 'Teleport Accurately',
  'temporal stasis': 'Temporal Inertia',
  'time stop': 'Time Control',
  'tiny hut': 'Tiny Realm',
  'tongues': 'Tongues',
  'transmute flesh and stone': 'Transform Flesh to Stone',
  'transmute metal to wood': 'Transform Metal to Wood',
  'transmute mud and rock': 'Transform Soft Soil to Stone',
  'transport via plants': 'Transport throught Plants',
  'trap the soul': 'Trap Entity',
  'treasure hoard': 'Treasure Hoard',
  'true resurrection': 'Resurrection without Error',
  'true seeing': 'Truth Revealed',
  'undetectable aura': 'Undetectable Aura',
  'unseen servant': 'Unseen Id',
  'wall of fire': 'Wall of Elemental Fire',
  'wall of force': 'Wall of Will',
  'wall of ice': 'Wall of Elemental Ice',
  'wall of iron': 'Wall of Resilient Alloy',
  'wall of stone': 'Wall of Elemental Earth',
  'wall of thorns': 'Wall of Bramble and Hedge',
  'wall of wind': 'Wall of Elemental Wind',
  'warp wood': 'Warp Timber',
  'water breathing': 'Water Breathing',
  'web': 'Web',
  'weird': 'Weirding',
  'wind walk': 'Wind Travel',
  'wish': 'Wish',
  'word of recall': 'Word to Sanctuary',
};

// Monster name mappings (M&T Names → Change)
export const MONSTER_NAME_MAPPINGS: Record<string, string> = {
  'aboleth': 'Abyssal Tyrant or Deep Tyrant',
  'achaierai': 'Achar Strider',
  'aerial servant': 'Aerial Watcher',
  'aetolian boar': 'Giant Boar',
  'agathion': 'Angelic Wanderer',
  'allip': 'Wraithwisp',
  'ankheg': 'Ankhorian Tunneler',
  'ant lion': 'Giant Ant Lion',
  'arrowhawk': 'Lightning Hawk',
  'ascomoid': 'Fungus, Sphereoid',
  'assassin vine': 'Strangleweed',
  'aurumvorax': 'Gold Gorger',
  'azer': 'Blazer',
  'babbler': 'Lizardfolk, Babbling',
  'badger (ratel)': 'Badger',
  'behir': 'Lightning Wyrm',
  'belker': 'Shadow Demon',
  'blindheim': 'Blinding Batrachian',
  'blink dog': 'Blink Hound',
  'boar, wild (razorback)': 'Boar, Wild',
  'boggle': 'Bogglyn',
  'bonesnapper': 'Bone Snapper',
  'bulette': 'Landshark',
  'caryatid columns': 'Golem, Columnar',
  'carterwaul': 'Caterwaul',
  'cave fisher': 'Cave Angler',
  'cloaker': 'Cloakling',
  'clubnek': 'Clubneck',
  'cooshee': 'Dog, Elven',
  'crabman': 'Crabfolk',
  'crypt thing': 'Crypt Lord',
  'crysmal': 'Crystal Creature',
  'cyclopes': 'Cyclops',
  'cenocephaly': 'Dogmen',
  'dakon': 'Ape, Dakon',
  'dark creeper': 'Darkling Creeper',
  'darkmantle': 'Roctopus',
  'dark stalker': 'Darkling Stalker',
  'death dog': 'Death Dog',
  'demilich': 'Demi-Lich',
  'derro': 'Derroh',
  'devil dog': 'Devil Dog',
  'devourer': 'Ethereal Devourer',
  'dire corby': 'Dread Corbie',
  'disenchanter': 'De-Enchanter',
  'doombat': 'Terror Bat',
  'dragonfish': 'Stonefish',
  'drelb': 'Drell Wraith',
  'drider': 'Arachnoid, Dark Elf',
  'duergar': 'Deep Dwarf',
  'dustdigger': 'Dustdweller',
  'ear seeker': 'Earwig',
  'eblis': 'Eblire',
  'elf, drow': 'Elf, Dark',
  'ettercap': 'Ettercap',
  'executioner\'s hood': 'Executioner\'s Hood',
  'eye killer': 'Batwinged Eye',
  'firedrake': 'Flamedrake',
  'firesnake': 'Flamesnake',
  'flail snail': 'Rainbow Mollusk',
  'flind': 'Gnoll, Greater',
  'flumph': 'Flumm',
  'forlarren': 'Forlorne',
  'frost men': 'Frostfolk',
  'frost worm': 'Ice Worm',
  'fungus, violet': 'Fungus, Purple',
  'gelatinous cube': 'Gelatinous Cube',
  'gib': 'Gib',
  'gibbering mouther': 'Gibbering Abomination',
  'gorbel': 'Six-Eyed Grappler',
  'gorgimera': 'Gorgimera',
  'gorilla bear': 'Bearilla',
  'green slime': 'Green Slime',
  'hag, annis': 'Hag, Agnes',
  'haunt': 'Hant',
  'hoar fox': 'Frost Fox',
  'hound of ill omen': 'Doom Dog',
  'huecuva': 'Doompriest',
  'hydra, pyrohydra': 'Hydra, Fire',
  'hydra, cryohydra': 'Hydra, Frost',
  'invisible stalker': 'Unseen Stalker',
  'iron cobra': 'Steel Serpent',
  'jaculi': 'Jack Serpent',
  'kamadan': 'Kamad Kat',
  'kech': 'Kekh',
  'kraken (leviathan)': 'Kraken',
  'land lamprey': 'Land Leech',
  'lava children': 'Lavillon',
  'locathah': 'Locath',
  'lurker': 'Lurker in Darkness',
  'lycanthrope, weretiger/leapard': 'Lycanthrope, Weretiger/Leopard',
  'magnesium spirit': 'Lumionous Spirit',
  'mantari': 'Mantareh',
  'margoyle': 'Gargoyle, Marine',
  'mephit, air': 'Impling, Air',
  'mephit, fire': 'Impling, Fire',
  'mephit, magma': 'Impling, Magma',
  'mephit, steam': 'Impling, Steam',
  'merrow': 'Ogre, Marine',
  'mihstu': 'Mist Monster',
  'mongrelmen': 'Mongrelfolk',
  'muck dweller': 'Muckosaurus',
  'mudman': 'Mud Man',
  'mushroomies': 'Mushroomie',
  'nachzehrer': 'Night Eater',
  'necrophidius': 'Death Serpent',
  'odmience': 'Changeling',
  'ogre mage': 'Ogre Magi',
  'ogrillon': 'Ogrillon',
  'ooze, black pudding': 'Ooze, Black Death',
  'ooze, ochre jelly': 'Ooze, Amber',
  'ophidian': 'Serpentfolk',
  'otyugh': 'Loathsome Dung Eater',
  'owlbear': 'Owlbear',
  'pech': 'Pehk',
  'phase spider': 'Void Spider',
  'phantom stalker': 'Pyric Stalker',
  'piercer': 'Impaler',
  'prismal eye (nonocculus)': 'Prismal Eye',
  'purple worm': 'Titan Worm',
  'pyrolisk': 'Cockatrice, Fire',
  'qual-man': 'Qual-Man',
  'quasit': 'Quasim',
  'remorhaz': 'Polar Annihilator',
  'retriever': 'Leng Spider',
  'roper': 'Cave Creeper',
  'russet mold': 'Mold, Rusted',
  'rust monster': 'Rust Fiend',
  'sahuagin': 'Sharkin',
  'sandling': 'Dust Devil',
  'sandman': 'Sandfolk',
  'screaming devilkin': 'Imp, Screaming',
  'shade': 'Shadeling',
  'shambling mound': 'Shambler',
  'skeletal warrior': 'Skeleton, Warrior',
  'skulk': 'Skulker',
  'sons of rhealth': 'Son of Rhealth',
  'stirge': 'Strix',
  'stone guardian': 'Stone Protector',
  'stun jelly': 'Slime, Stunning',
  'taer': 'Skunk Ape',
  'tail-goblins': 'Tail-Goblin',
  'tarrasque': 'Apocalypse Bringer',
  'thessalhydra': 'Terrorhydra',
  'thoqqua': 'Thoggua',
  'throat leech': 'Leafleech',
  'thirs': 'Thir Goblin',
  'valkryja': 'Valkarie',
  'vargouille': 'Vargweel',
  'vegepygmy': 'Veggepygmy',
  'volt': 'Voltwhip',
  'wind walker': 'Wind Stalker',
  'witherstench': 'Witherrat',
  'xorn': 'Xork',
  'yellow mold': 'Mold, Yellow',
  'yeth hound': 'Yethian Hound',
  'yrthak': 'Yeerthak',
};

// Magic item mappings with mechanical explanations
export const MAGIC_ITEM_MAPPINGS: Record<string, string> = {
  'robe of protection': 'robe of armor',
  'ring of protection': 'ring of armor',
  'dagger of venom': 'dagger of envenomation',
  'pectoral of protection': 'pectoral of armor',
};

// Magic item mechanical explanations
// NO MAGIC ITEM CAN BE PRINTED WITHOUT SOME DEGREE OF MECHANICAL EXPLANATION
export const MAGIC_ITEM_MECHANICS: Record<string, string> = {
  // Armor Items
  'robe of armor': 'AC +1 to +5',
  'ring of armor': 'AC +1 to +5',
  'pectoral of armor': 'AC +1 to +3',
  'bracers of defense': 'AC +1 to +8',
  'cloak of protection': 'AC +1 to +5, saves +1 to +5',
  'shield': 'AC +1 to +5',
  'medium steel shield': 'AC +1',

  // Weapons
  'dagger of envenomation': 'save vs. poison or die',
  'sword of sharpness': '+1 to +5, severs limbs on natural 20',
  'frost brand': '+3 vs. fire creatures, immunity to fire',
  'flame tongue': '+1 to +5, +2d6 fire damage',
  'holy avenger': '+5 vs. evil, spell resistance',
  'vorpal blade': 'severs head on natural 20',

  // Potions
  'potion of healing': 'heals 1d8+1 HP',
  'potion of extra healing': 'heals 2d8+2 HP',
  'potion of heroism': '+2 to attacks, saves, and damage for 1 hour',
  'potion of giant strength': 'strength 18/00 for 1 hour',
  'potion of invisibility': 'invisible for 1 hour or until attacking',

  // Rings
  'ring of regeneration': 'regains 1 HP per round',
  'ring of spell storing': 'stores 1-5 spell levels',
  'ring of wizardry': 'doubles 1st-3rd level spells',
  'ring of telekinesis': 'telekinesis at will',
  'ring of invisibility': 'invisible at will',

  // Wands and Staves
  'wand of fireballs': '6d6 damage, 20 charges',
  'wand of lightning bolts': '6d6 damage, 20 charges',
  'staff of power': 'various spells, 50 charges',
  'staff of the magi': 'powerful spells, 50 charges',

  // Miscellaneous
  'bag of holding': 'holds 10,000 coins weight',
  'boots of speed': 'double movement rate',
  'gauntlets of ogre power': 'strength 18/00',
  'helm of telepathy': 'ESP and suggestion',
  'amulet of life protection': 'prevents level drain',
  'crystal ball': 'scrying device',
  'deck of many things': 'random magical effects',
  'portable hole': 'extradimensional space',

  // Standard bonuses (catch-all for +X items)
  '+1': '+1 bonus',
  '+2': '+2 bonus',
  '+3': '+3 bonus',
  '+4': '+4 bonus',
  '+5': '+5 bonus',
};

// Function to detect if an item is magical
export function isMagicalItem(item: string): boolean {
  const magicIndicators = [
    /\+\d+/,                                    // Has bonus like +1, +2, etc.
    /\bof\s+\w+/i,                             // "of something" format
    /\b(ring|wand|staff|rod|potion|scroll)\b/i, // Common magic item types
    /\b(magic|magical|enchanted)\b/i,          // Explicit magic words
    /\b(holy|unholy|blessed|cursed)\b/i,       // Religious items
  ];

  return magicIndicators.some(pattern => pattern.test(item));
}

// Function to add mechanical explanations to magic items
export function addMagicItemMechanics(item: string): string {
  if (!isMagicalItem(item)) {
    return item;
  }

  // Check for exact matches first
  const lowerItem = item.toLowerCase().trim();
  if (MAGIC_ITEM_MECHANICS[lowerItem]) {
    return `${item} (${MAGIC_ITEM_MECHANICS[lowerItem]})`;
  }

  // Check for partial matches
  for (const [itemName, mechanics] of Object.entries(MAGIC_ITEM_MECHANICS)) {
    if (lowerItem.includes(itemName.toLowerCase())) {
      return `${item} (${mechanics})`;
    }
  }

  // Handle +X bonuses
  const bonusMatch = item.match(/\+(\d+)/);
  if (bonusMatch) {
    const bonus = bonusMatch[1];
    if (MAGIC_ITEM_MECHANICS[`+${bonus}`]) {
      return `${item} (${MAGIC_ITEM_MECHANICS[`+${bonus}`]})`;
    }
  }

  // If no specific mechanics found, add generic explanation
  return `${item} (see Appendix: Magic Items)`;
}

// Helper function to apply all name mappings
export function applyNameMappings(text: string): string {
  let result = text;

  // Apply spell mappings
  for (const [oldName, newName] of Object.entries(SPELL_NAME_MAPPINGS)) {
    const regex = new RegExp(`\\b${oldName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi');
    result = result.replace(regex, newName);
  }

  // Apply monster mappings
  for (const [oldName, newName] of Object.entries(MONSTER_NAME_MAPPINGS)) {
    const regex = new RegExp(`\\b${oldName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi');
    result = result.replace(regex, newName);
  }

  // Apply magic item mappings
  for (const [oldName, newName] of Object.entries(MAGIC_ITEM_MAPPINGS)) {
    const regex = new RegExp(`\\b${oldName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi');
    result = result.replace(regex, newName);
  }

  return result;
}