// Comprehensive name mappings for C&C edition changes
// Generated from the CnC Name Changes spreadsheets

// Spell name mappings (Original → New Name)
export const SPELL_NAME_MAPPINGS: Record<string, string> = {
  'acid arrow': 'Acidic Bolt',
  'air/water walk': 'Air/Water Stride',
  'alter self': 'Alter One\'s Person Greater',
  'alter size': 'Alter Size',
  'animal friendship': 'Animal Bond',
  'animal growth': 'Animal Alteration',
  'animal messenger': 'Animal Courier',
  'animal shapes': 'Animal Form',
  'animate dead': 'Animate Corpse',
  'anti-illusion shield': 'Anti Illusion Sphere',
  'anti-life shell': 'Anti Life Sphere',
  'anti-magic shell': 'Anti Magic Sphere',
  'anti-plant shell': 'Anti Plant Sphere',
  'arcane eye': 'Arcane Vision',
  'arcane mark': 'Arcane Rune',
  'astral projection': 'Astral Travel',
  'banishment': 'Banishment',
  'barkskin': 'Barkform',
  'binding': 'Bind',
  'blade barrier': 'Blade Blockade',
  'bless': 'Bless',
  'bless water': 'Blessing Water',
  'burning hands': 'Burning Flames',
  'call lightning': 'Conjure Lightning',
  'calm animals': 'Calm Animals',
  'change self': 'Alter One\'s Person Lesser',
  'changestaff': 'Change Stave to Treant',
  'charm person': 'Charm Humanoid',
  'charm person or animal': 'Charm Humanoid or Animal',
  'cloak of dark chaos': 'Cloak of Smoke and Darkness',
  'cloudkill': 'Cloud of Pestilence',
  'color spray': 'Colors',
  'command plants': 'Command Plants',
  'commune': 'Commune',
  'commune with nature': 'Commune with the Natural World',
  'comprehend languages': 'Comprehension',
  'cone of cold': 'Cone of Winter\'s Blast',
  'consecrate': 'Consecrate',
  'contact other plane': 'Contact Other Worlds',
  'continual flame': 'Continual Fire',
  'control plants': 'Control Plants',
  'control water': 'Control Liquids',
  'control weather': 'Control Atmosphere',
  'control winds': 'Control Gales',
  'create food and water': 'Create Sustenance',
  'create greater undead': 'Create Common & Extraordinary Undead',
  'create undead': 'Create Unique Undead',
  'create water': 'Create Water',
  'creeping doom': 'Creeping Swarm',
  'cure light wounds': 'Heal Light Wounds',
  'cure critical wounds': 'Heal Critical Wounds',
  'cure serious wounds': 'Heal Serious Wounds',
  'dancing lights': 'Dancing Orbs',
  'dark chaos': 'Dark Whips',
  'darkness': 'Darkness',
  'death ward': 'Death Mask',
  'delay poison': 'Delay Toxin',
  'delayed blast fireball': 'Delayed Fireball',
  'detect alignment': 'Detect Disposition',
  'detect illusion': 'Discern Illusion',
  'detect magic': 'Discern Magic',
  'detect neutrality': 'Detect Disposition',
  'detect poison': 'Discover Poison',
  'detect scrying': 'Discern Scrying',
  'detect secret doors': 'Discover Secret Doors',
  'detect snares and pits': 'Discover Snares and Pits',
  'detect thoughts': 'Discern Thoughts',
  'detect traps': 'Discover Traps',
  'detect undead': 'Discover Undead',
  'dimension door': 'Dimensional Leap',
  'discern lies': 'Discern Falsehood',
  'discern location': 'Discover Location',
  'dispel alignment': 'Dispel Disposition',
  'displaced image': 'Displace',
  'distort reality': 'Distort Reality',
  'double treasure': 'Doubled Treasure',
  'endure elements': 'Endure Cold/Heat',
  'energy drain': 'Energy Level Drain',
  'enhance attribute': 'Enhance an Attribute',
  'entangle': 'Entangling Vegetation',
  'ethereal jaunt': 'Ethereal Jump',
  'explosive runes': 'Explosive Mark',
  'eyes of fire': 'Eyes of Chaos',
  'faerie fire': 'Faerie Aura',
  'faeries glamour': 'Faerie Reflection',
  'faithful hound': 'Faithful Watchdog',
  'false trap': 'False Snare or Trap',
  'false vision': 'False Scrying',
  'feather fall': 'Feather Light',
  'find the path': 'Finding Trails',
  'finger of death': 'Fatal Gesture',
  'fireball': 'Fireballs',
  'fire seeds': 'Flame Seeds',
  'fire shield': 'Flame Shield',
  'fire storm': 'Flaming Tempest',
  'fire trap': 'Flame Snare',
  'flame strike': 'Flame of the Divine',
  'floating disc': 'Flying Saucer',
  'fog cloud': 'Fog',
  'freedom of movement': 'Free Motion',
  'gaseous form': 'Gas Form',
  'ghost sound': 'Ghostly Noise',
  'globe of invulnerability': 'Globe of Spell Protection',
  'glyph of warding': 'Glyphs',
  'goodberry': 'Good Fruit',
  'greater restoration': 'Restoration',
  'greater scrying': 'Scrying',
  'greater shadow conjuration': 'Conjure Phantasm',
  'greater shadow evocation': 'Evoke Arcane Phantasm',
  'guards and wards': 'Guard with Wards',
  'gust of wind': 'Gust',
  'hallow': 'Hallow',
  'hallucinatory terrain': 'Hallucinatory Ground',
  'haste': 'Haste',
  'heal': 'Heal',
  'healing circle': 'Healing Sphere',
  'heat metal': 'Heat any Alloy',
  'hold animal': 'Hold Animals and Plants',
  'hold monster': 'Hold Creature',
  'hold person': 'Hold Humanoid',
  'hold portal': 'Hold & Bar Gate',
  'holy aura': 'Holy Glamour',
  'holy word': 'Holy Utterance',
  'humanoid finding': 'Humanoid Finding',
  'hypnotic pattern': 'Hypnotic Imagery',
  'hypnotism': 'Hypnotism',
  'ice storm': 'Ice Storm',
  'illusionary help': 'Illusionary Help',
  'illusory hounds': 'Illusionary Hounds',
  'illusionary lions': 'Illusionary Lions',
  'illusory script': 'Illusory Writing',
  'illusory wall': 'Illusory Barrier',
  'imprisonment': 'Imprison',
  'improved invisibility': 'Invisibility Heightened',
  'incendiary cloud': 'Incendiary Flow',
  'insect plague': 'Insect Swarm',
  'instant summons': 'Instant Item',
  'invisible': 'Invisibility',
  'invisibility sphere': 'Invisibility Orb',
  'invisibility to animals': 'Invisibility to Animals',
  'invisibility to undead': 'Invisible Cloak of the Undead',
  'ironwood': 'Ironbark',
  'know direction': 'Know the Path',
  'legend lore': 'Legendary Tales',
  'lesser restoration': 'Restoration',
  'lightning bolt': 'Lightning',
  'limited wish': 'Wish, Minor',
  'locate creature': 'Locate Other',
  'locate object': 'Locate Item',
  'mage hand': 'Magi\'s Reach',
  'magic aura': 'Magi\'s Glamour',
  'magic jar': 'Magi\'s Vessel',
  'magic missile': 'Magi\'s Missile',
  'magic mouth': 'Magi\'s Visage',
  'magic stones': 'Magic Sling',
  'major creation': 'Magi\'s Conjuring',
  'major dark chaos': 'Major Dark Whips',
  'major image': 'Illusion',
  'mass charm': 'Charm Area',
  'mass heal': 'Heal in Area',
  'mass invisibility': 'Invisibility in Area',
  'mass suggestion': 'Suggestion in Area',
  'meld into stone': 'Meld',
  'mending': 'Mending',
  'meteor swarm': 'Meteor Shower',
  'mind blank': 'Mind Ward',
  'minor dark chaos': 'Minor Dark Whips',
  'minor creation': 'Minor Concoction',
  'minor globe of invulnerability': 'Minor Globe of Spell Protection',
  'minor image': 'Illusion',
  'mirage arcana': 'Mirage',
  'mirror image': 'Mirrored Self',
  'mislead': 'Misguide',
  'mnemonic enhancer': 'Mnemonic Enhancement',
  'move earth': 'Harrow the Earth',
  'neutralize poison': 'Neutralize Toxins',
  'nondetection': 'Nondetection',
  'obscuring mist': 'Obscure with Mist',
  'open/close': 'Open/Close',
  'passwall': 'Passage',
  'pass without trace': 'Pass with Woodland Stride',
  'permanent image': 'Perpetual Illusion',
  'persistent image': 'Persevering Illusion',
  'phantasmal killer': 'Phantasm',
  'phase door': 'Phase through Obstruction',
  'plane shift': 'Planar Travel',
  'plant growth': 'Plant Growth',
  'polymorph any object': 'Polymorph Creatures & Things',
  'polymorph other': 'Polymorph Creature',
  'polymorph self': 'Polymorph Own Person',
  'power word blind': 'Power of the Spoken Word: Purblind',
  'power word kill': 'Power of the Spoken Word: Slay',
  'power word stun': 'Power of the Spoken Word: Immobilize',
  'prismatic sphere': 'Polychromatic Sphere',
  'prismatic spray': 'Polychromatic Spray',
  'prismatic wall': 'Polychromatic Wall',
  'produce flame': 'Produce Fire',
  'programmed image': 'Programmed Illusion',
  'project image': 'Projection',
  'protection from alignment': 'Protection from Disposition',
  'protection from arrows': 'Protection from Normal Missiles',
  'protection from elements': 'Protection from Elemental Attacks',
  'purify food and drink': 'Purify',
  'rainbow pattern': 'Rainbow',
  'raise dead': 'Raise',
  'ray of enfeeblement': 'Ray of Weakening',
  'read magic': 'Read Arcane Script',
  'remove blindness or deafness': 'Restore Sight & Hearing',
  'remove curse': 'Remove Bane',
  'remove disease': 'Remove Malady',
  'remove fear': 'Remove Despair',
  'remove paralysis': 'Restore Movement',
  'repel metal or stone': 'Remove Alloy and Stone from Path',
  'repel vermin': 'Repel Pest',
  'repel wood': 'Remove Wood from Path',
  'resilient sphere': 'Resilient Globe',
  'resist elements': 'Resist One Element',
  'restoration': 'Restoration',
  'rope trick': 'Rope Dimension',
  'secret chest': 'Secret Container',
  'secret page': 'Secret Script',
  'secure shelter': 'Shelter',
  'see invisibility': 'See Invisible',
  'seeming': 'Seeming',
  'sending': 'Send',
  'shades': 'Shades',
  'shadow conjuration': 'Shadow Convocation',
  'shadow evocation': 'Shadow Sorcery',
  'shadow walk': 'Shadow Journey',
  'shapechange': 'Shapeshift',
  'shape stone or wood': 'Shape Stone or Wood',
  'shield of faith': 'Shield of the Divine',
  'shocking grasp': 'Shock',
  'silent image': 'Silent Illusion',
  'sleet storm': 'Sleet',
  'solid fog': 'Solidlike Fog',
  'soul bind': 'Soul to Gem',
  'sound burst': 'Sound Storm',
  'speak with animals': 'Speak with Animals',
  'speak with dead': 'Speak with the Dead',
  'speak with plants': 'Speak with Plants',
  'spider climb': 'Spider Walk',
  'spike stones': 'Spike Spell',
  'spiritual weapon': 'Spiritual Warrior',
  'stinking cloud': 'Stench',
  'stone tell': 'Stone Speak',
  'storm of vengeance': 'Storm of Wrath',
  'summon animal': 'Summon Animals',
  'summon beasts or plants': 'Summon Beasts and Plants',
  'summon elemental': 'Summon Elemental Being',
  'summon elemental swarm': 'Summon Elemental Horde',
  'summon familiar': 'Summon Familiar',
  'summon greater monster': 'Summon Monstrous Ally',
  'summon lesser monster': 'Summon Monstrous Ally',
  'summon magical beast or fey': 'Summon Fey and Magical Beasts',
  'summon monster': 'Summon Monstrous Ally',
  'summon planar ally': 'Summon Extraplanary Ally',
  'summon swarm': 'Summon Pests',
  'sunburst': 'Sun Flare',
  'telepathic bond': 'Telepathy',
  'teleport': 'Teleportation',
  'teleportation circle': 'Teleportation Field',
  'teleport without error': 'Teleport Accurately',
  'temporal stasis': 'Temporal Inertia',
  'time stop': 'Time Control',
  'tiny hut': 'Tiny Realm',
  'tongues': 'Tongues',
  'transmute flesh and stone': 'Transform Flesh to Stone',
  'transmute metal to wood': 'Transform Metal to Wood',
  'transmute mud and rock': 'Transform Soft Soil to Stone',
  'transport via plants': 'Transport throught Plants',
  'trap the soul': 'Trap Entity',
  'treasure hoard': 'Treasure Hoard',
  'true resurrection': 'Resurrection without Error',
  'true seeing': 'Truth Revealed',
  'undetectable aura': 'Undetectable Aura',
  'unseen servant': 'Unseen Id',
  'wall of fire': 'Wall of Elemental Fire',
  'wall of force': 'Wall of Will',
  'wall of ice': 'Wall of Elemental Ice',
  'wall of iron': 'Wall of Resilient Alloy',
  'wall of stone': 'Wall of Elemental Earth',
  'wall of thorns': 'Wall of Bramble and Hedge',
  'wall of wind': 'Wall of Elemental Wind',
  'warp wood': 'Warp Timber',
  'water breathing': 'Water Breathing',
  'web': 'Web',
  'weird': 'Weirding',
  'wind walk': 'Wind Travel',
  'wish': 'Wish',
  'word of recall': 'Word to Sanctuary',
};

// Monster name mappings from master_monster reforged mappings (1).csv
export const MONSTER_NAME_MAPPINGS: Record<string, string> = {
  'aboleth': 'Abhorrent',
  'aerial servant': 'Aerial Thrall',
  'algoid': 'Algoid',
  'allip': 'Wraithwisp',
  'ankheg': 'Ankh Mantis',
  'amphisbaena': 'Amphisbaena',
  'ant, giant': 'Ant, Giant',
  'ant lion': 'Ant Lion, Giant',
  'apparition': 'Apparition',
  'arrowhawk': 'Airhawk',
  'ascomoid': 'Fungus, Globular',
  'assassin vine': 'Strangleweed',
  'aurumvorax': 'Aurum Beast',
  'avia': 'Avia',
  'azer': 'Aiser',
  'banderlog': 'Banderlog',
  'banshee': 'Banshee',
  'basilisk': 'Basilisk',
  'basilisk, greater': 'Basilisk, Greater',
  'bauk': 'Bauk',
  'behir': 'Behemoth',
  'belker': 'Bel Demon',
  'berbalang': 'Berbalang',
  'blink dog': 'Blink Hound',
  'bloodsucking wyrm': 'Bloodsucking Wyrm',
  'bodak': 'Bodak',
  'boggle': 'Bogglyn',
  'bonesnapper': 'Bone Snapper',
  'bugbear': 'Bugbear',
  'bulette': 'Boolay',
  'cadaver caterpillar': 'Cadaver Caterpillar',
  'catoblepas': 'Catoblepas',
  'cave fisher': 'Cave Fisher',
  'centipede, giant': 'Centipede, Giant',
  'centaur': 'Centaur',
  'chawl witch': 'Chawl Witch',
  'chimera': 'Chimera',
  'chort': 'Chort',
  'chuhaister': 'Chuhaister',
  'claret wraith': 'Claret Wraith',
  'cloaker': 'Cloaker',
  'cockatrice': 'Cockatrice',
  'coffer corpse': 'Coffer Corpse',
  'couatl': 'Couatl',
  'crab, giant': 'Crab, Giant',
  'crypt thing': 'Crypt Keeper',
  'cyclopes': 'Cyclopes',
  'dark creeper': 'Darkling Creeper',
  'darkmantle': 'Dark Mantle',
  'dark stalker': 'Darkling Stalker',
  'death knight': 'Death Knight',
  'demilich': 'Demilich',
  'devil dog': 'Devil Hound',
  'dinosaur, triceratops': 'Dinosaur, Triceratops',
  'dinosaur, tyrannosaurus': 'Dinosaur, Tyrannosaurus',
  'dire corby': 'Dire Corvid',
  'disenchanter': 'Disenchanter',
  'doppelganger': 'Doppelganger',
  'dragon, black': 'Dragon, Black',
  'dragon, blue': 'Dragon, Blue',
  'dragon, green': 'Dragon, Green',
  'dragon, red': 'Dragon, Red',
  'dragon, white': 'Dragon, White',
  'dragon, brass': 'Dragon, Brass',
  'dragon, bronze': 'Dragon, Bronze',
  'dragon, copper': 'Dragon, Copper',
  'dragon, gold': 'Dragon, Gold',
  'dragon, silver': 'Dragon, Silver',
  'dragonne': 'Dragonne',
  'draugr': 'Draugr',
  'drider': 'Dridaur',
  'dryad': 'Dryad',
  'duergar': 'Duergar',
  'dune wraith': 'Dune Wraith',
  'dwarf': 'Dwarf',
  'eagle, giant': 'Eagle, Giant',
  'ear seeker': 'Earwig',
  'elemental, air': 'Elemental, Air',
  'elemental, earth': 'Elemental, Earth',
  'elemental, fire': 'Elemental, Fire',
  'elemental, water': 'Elemental, Water',
  'elephant': 'Elephant',
  'elf': 'Elf',
  'elf, drow': 'Elf, Dark',
  'ettercap': 'Ettercop',
  'ettin': 'Ettin',
  'evil occulus of ice and fire': 'Evil Occulus',
  'firbolg': 'Firbolg',
  'firedrake': 'Firedrake',
  'fleshcrawler': 'Fleshcrawler',
  'flind': 'Flinnoll',
  'frog, giant': 'Frog, Giant',
  'frost worm': 'Frost Worm',
  'fungus, violet': 'Fungus, Violent',
  'gargoyle': 'Gargoyle',
  'gelatinous cube': 'Ooze, Gelatinous',
  'genie, djinni': 'Genie, Djinni',
  'genie, efreeti': 'Genie, Efreeti',
  'ghast': 'Ghast',
  'ghost': 'Ghost',
  'ghoul': 'Ghoul',
  'giant, cloud': 'Giant, Cloud',
  'giant, fire': 'Giant, Fire',
  'giant, frost': 'Giant, Frost',
  'giant, hill': 'Giant, Hill',
  'giant, stone': 'Giant, Stone',
  'giant, storm': 'Giant, Storm',
  'gibbering mouther': 'Gibbering Madness',
  'gig': 'Gig',
  'gnoll': 'Gnoll',
  'gnome': 'Gnome',
  'goblin': 'Goblin',
  'golem, clay': 'Golem, Clay',
  'golem, flesh': 'Golem, Flesh',
  'golem, iron': 'Golem, Iron',
  'golem, stone': 'Golem, Stone',
  'gorgon': 'Gorgon',
  'gravelor': 'Gravelor',
  'green slime': 'Green Slime',
  'griffon': 'Griffon',
  'gromm': 'Gromm',
  'grue': 'Grue',
  'hag, annis': 'Hag, Agnes',
  'hag, green': 'Hag, Green',
  'hag, night': 'Hag, Night',
  'halfling': 'Halfling',
  'hangman\'s tree': 'Hangman\'s Tree',
  'harpy': 'Harpy',
  'haunt': 'Haunt',
  'hellhound': 'Hellhound',
  'herd animal': 'Herd Animal',
  'hippocampus': 'Hippocampus',
  'hippogriff': 'Hippogriff',
  'hobgoblin': 'Hobgoblin',
  'homunculus': 'Homunculus',
  'horse': 'Horse',
  'hook fiend': 'Hook Fiend',
  'huecuva': 'Hexuva',
  'human': 'Human',
  'hydra': 'Hydra',
  'hydra, pyrohydra': 'Hydra, Fire',
  'hydra, cryohydra': 'Hydra, Frost',
  'imp': 'Imp',
  'insectus': 'Insectus',
  'invisible stalker': 'Invisible Skulker',
  'iron cobra': 'Iron Serpent',
  'jaculus': 'Jaculus',
  'jarim': 'Jarim',
  'kech': 'Ketch',
  'kobold': 'Kobold',
  'korred': 'Korred',
  'kraken': 'Kraken',
  'kyreen': 'Kyreen',
  'lamia': 'Lamia',
  'lamia queen': 'Lamia Queen',
  'lammasu': 'Lammasu',
  'lich': 'Lich',
  'lion': 'Lion',
  'lizard, giant': 'Lizard, Giant',
  'lizardfolk': 'Lizardfolk',
  'lizard lord': 'Lizard Lord',
  'locathah': 'Loclan',
  'lurker': 'Lurker in Darkness',
  'lycanthrope, werebear': 'Lycanthrope, Werebear',
  'lycanthrope, wereboar': 'Lycanthrope, Wereboar',
  'lycanthrope, werefox': 'Lycanthrope, Werefox',
  'lycanthrope, wererat': 'Lycanthrope, Wererat',
  'lycanthrope, weresnake': 'Lycanthrope, Weresnake',
  'lycanthrope, werespider': 'Lycanthrope, Werespider',
  'lycanthrope, weretiger/leapard': 'Lycanthrope, Weretiger/Leopard',
  'lycanthrope, werewolf': 'Lycanthrope, Werewolf',
  'lynx, giant': 'Lynx, Giant',
  'magmafolk': 'Moltenn',
  'manticore': 'Manticore',
  'medusa': 'Medusa',
  'mephit, air': 'Impling, Air',
  'mephit, fire': 'Impling, Fire',
  'mephit, magma': 'Impling, Magma',
  'mephit, steam': 'Impling, Steam',
  'merrow': 'Ogre, Marine',
  'mimic': 'Mimic',
  'minotaur': 'Minotaur',
  'mudman': 'Mudman',
  'mummy': 'Mummy',
  'mushroomies': 'Mycelians',
  'nachzehrer': 'Night Eater',
  'naga, dark': 'Naga, Dark',
  'naga, ghost': 'Naga, Ghost',
  'naga, guardian': 'Naga, Guardian',
  'naga, spirit': 'Naga, Spirit',
  'naga, water': 'Naga, Water',
  'necrophidius': 'Necroserpent',
  'needler': 'Needler',
  'nereid': 'Nereid',
  'nightmare': 'Nightmare',
  'nomore\'': 'Nomore',
  'nymph': 'Nymph',
  'ogre': 'Ogre',
  'ogre mage': 'Ogre Magi',
  'ogrerat': 'Ogrerat',
  'ooze, black pudding': 'Ooze, Black Pudding',
  'ooze, gray': 'Ooze, Gray',
  'ooze, ochre jelly': 'Ooze, Ochre Jelly',
  'ophidian': 'Ophidian',
  'orc': 'Orc',
  'osmosious': 'Osmosious',
  'otyugh': 'Otyvore',
  'owlbear': 'Owlbear',
  'pech': 'Peck',
  'pegasus': 'Pegasus',
  'phase spider': 'Void Spider',
  'penanggalan': 'Penanggalan',
  'peryton': 'Peryton',
  'phoenix': 'Phoenix',
  'piercer': 'Piercer',
  'poltergeist': 'Poltergeist',
  'pony': 'Pony',
  'prismal eye': 'Prismal Eye',
  'pseudodragon': 'Pseudodragon',
  'purple worm': 'Purple Titan Worm',
  'quasit': 'Quasidemon',
  'quickling': 'Quickling',
  'rakshasa': 'Rakshasa',
  'rat, giant': 'Rat, Giant',
  'raven': 'Raven',
  'remorhaz': 'Rime Horror',
  'retriever': 'Reever',
  'revenant': 'Revenant',
  'roc': 'Roc',
  'rock reptile': 'Rock Reptile',
  'roper': 'Roping Lurker',
  'ruel': 'Ruel',
  'russet mold': 'Rusted Mold',
  'rust monster': 'Rust Fiend',
  'sahuagin': 'Sharkin',
  'salamander': 'Salamander',
  'satyr': 'Satyr',
  'scarecrow': 'Scarecrow',
  'screaming devilkin': 'Screaming Fiend',
  'screecher': 'Screecher',
  'selkie': 'Selkie',
  'sirens': 'Siren',
  'shade': 'Shade',
  'shadow': 'Shadow',
  'shambling mound': 'Shambling Muck',
  'shark': 'Shark',
  'sheen': 'Sheen',
  'shelkerow': 'Shelkerow',
  'skeletal warrior': 'Skeletal Warrior',
  'skeleton': 'Skeleton',
  'skeleton, animal': 'Skeleton, Animal',
  'snake': 'Snake',
  'sons of rhealth': 'Sons of Rhealth',
  'spectre': 'Spectre',
  'sphinx, andro-': 'Sphinx, Andro-',
  'sphinx, crio-': 'Sphinx, Crio-',
  'sphinx, gyno-': 'Sphinx, Gyno-',
  'sphinx, hieraco-': 'Sphinx, Hieraco-',
  'spider': 'Spider',
  'stirge': 'Strix',
  'stun jelly': 'Slime, Stunning',
  'svirfneblin': 'Svirfneblin',
  'tail-goblins': 'Tail-Goblin',
  'tarrasque': 'Tarrasque',
  'tavis wyrm': 'Tavis Wyrm',
  'throat leech': 'Throat Leech',
  'tick, giant': 'Tick, Giant',
  'tiger': 'Tiger',
  'titan': 'Titan',
  'toad, giant': 'Toad, Giant',
  'treant': 'Treant',
  'troglodyte': 'Troglodyte',
  'troll': 'Troll',
  'unicorn': 'Unicorn',
  'vampire': 'Vampire',
  'vegepygmy': 'Verdurekin',
  'volt': 'Voltwhip',
  'wight': 'Wight',
  'will-o\'-wisp': 'Will-o\'-Wisp',
  'wolf': 'Wolf',
  'worg': 'Worg',
  'winter wolf': 'Winter Wolf',
  'wraith': 'Wraith',
  'wyvern': 'Wyvern',
  'xa': 'Xa',
  'xorn': 'Zorn',
  'xsayarsa': 'Xsayarsa',
  'yellow mold': 'Yellow Mold',
  'yellow musk creeper': 'Yellow Haze Creeper',
  'yellow musk zombie': 'Yellow Haze Zombie',
  'yeth hound': 'Yeth Hound',
  'yeti': 'Yeti',
  'zombie': 'Zombie',
  'zombie, monster': 'Zombie, Monster'
};

// Magic item mappings from master_magic item.conversion.csv
export const MAGIC_ITEM_MAPPINGS: Record<string, string> = {
  // Potions
  'potion of giant strength': 'Potion of Giant Strength',
  'potion of longevity': 'Potion of Youth',
  'potion of protection from alignment': 'Potion of Protection from Dispostion',
  'potion of trap the soul': 'Potion of Trap Entity',
  'scroll of restoration': 'Scroll of Restoration (Least, Lesser, Greater, Greatest)',
  'scroll of protection': 'Scroll of Protection',
  'scroll of anti-magic shell': 'Scroll of Anti-Magic Sphere',
  'scroll of heal': 'Scroll of Heal',
  
  // Swords
  'bane sword': 'Bane Sword',
  'sword of dancing': 'Sword of Dancing',
  'sword of defending': 'Sword of Defending',
  'dragon slayer': 'Dragonslayer',
  'featheredged sword': 'Featheredged Sword',
  'flaming sword': 'Flaming Sword',
  'frost brand': 'Frostfire',
  'holy avenger': 'Holy Avenger',
  'sword of life stealing': 'Sword of Life Thieving',
  'luck blade': 'Luck Blade',
  'nine lives stealer': 'Nine Lives Thief',
  'sword of puncturing': 'Sword of Puncturing',
  'sylvan blade': 'Sylvan Blade',
  'vorpal sword': 'Vorpal Sword',
  'sword of wounding': 'Sword of Stinging',
  
  // Weapons
  'bane weapon': 'Bane Weapon',
  'club of dagda': 'Club of Dagda',
  'dagger of venom': 'Dagger of Envenomation',
  'dwarven thrower': 'Dwarven Hammer of Throwing',
  'featheredged axe': 'Featheredged Axe',
  'javelin of lightning': 'Lightning Javelin',
  'mace of disruption': 'Mace of Turning',
  'hammer of disruption': 'Mace of Turning',
  'mace of smiting': 'Mace of Banishment',
  'mace of terror': 'Mace of Scourge',
  'oathbow': 'Oathkeeper Bow',
  'slaying arrow': 'Arrow of Slaying',
  'sleep arrow': 'Sleep Arrow',
  'sylvan weapon': 'Sylvan Weapon',
  'trident of fish command': 'Trident of Sea Creature Command',
  'weapon of wounding': 'Weapon of Stinging',
  
  // Armor
  'armor of cold resistance': 'Armor of Cold Resistance',
  'armor of etherealness': 'Armor of the Ethereal Knight',
  'armor of fire resistance': 'Armor of Fire Resistance',
  'armor of kavacha': 'Armor of Kavacha',
  'armor of spell resistance': 'Armor of Spell Resistance',
  'animated shield': 'Animated Shield',
  'blinding shield': 'Blinding Shield',
  'dwarven plate': 'Dwarven Fullplate',
  'elven chain': 'Elven Chainmail',
  'lion\'s shield': 'Shield of the Roaring Lion',
  'plate armor of the deep': 'Plate Armor of the Diver',
  'shield of bashing': 'Shield of Attack',
  'shield of el cid': 'Shield of El Cid',
  
  // Amulets & Items
  'amulet of health': 'Amulet of Superior Health',
  'amulet of mighty fists': 'Amulet of Mighty Blows',
  'amulet of natural armor': 'Amulet of Bestial Armor',
  'amulet of the planes': 'Amulet of Planar Travel',
  'bag of holding': 'Dimensional Pouch',
  'bag of tricks': 'Bag of Beasts',
  'belt of giant strength': 'Harness of Giant Strength',
  'blessed book': 'Book of Budget-Conscious Spellcraft',
  'boat, folding': 'Boat, Foldable',
  'boots of elvenkind': 'Boots of the Elves',
  'boots of levitation': 'Boots of Levitation',
  'boots of speed': 'Boots of Flight of Foot',
  'boots of striding and springing': 'Boots of Striding and Leaping',
  'boots of teleportation': 'Boots of Teleporting',
  'boots of the winterlands': 'Boots of the Winter Dark',
  'bowl of commanding water elementals': 'Bowl of Elemental Water Command',
  'bracers of armor': 'Bracers of Armor',
  'bracers of deflection': 'Bracers of Deflecting',
  'brazier of commanding fire elementals': 'Brazier of Elemental Fire Command',
  'brooch of shielding': 'Brooch of Shielding',
  'broom of flying': 'Flying Broomstick',
  'candle of invocation': 'Priest\'s Candle',
  'cape of the mountebank': 'Trickster\'s Cape',
  'carpet of flying': 'Flying Carpet',
  'censer of commanding air elementals': 'Censer of Elemental Air Command',
  'chime of interruption': 'Chime of Discordance',
  'chime of opening': 'Opening Chime',
  'circlet of persuasion': 'Circlet of Charisma',
  'cloak of arachnida': 'Cloak of the Spider',
  'cloak of the bat': 'Cloak of the Bat',
  'cloak of charisma': 'Cloak of Charisma',
  'cloak of displacement': 'Cloak of Distortion',
  'cloak of elvenkind': 'Cloak of the Elves',
  'cloak of etherealness': 'Cloak of Ethereal Travel',
  'cloak of the manta ray': 'Cloak of the Ray',
  'cloak of resistance': 'Cloak of Resistance',
  'coin, sampo': 'Sampo Coin',
  'crystal ball': 'Crystal ball',
  'cube of force': 'Cube of Force',
  'cube of frost resistance': 'Cube of Cold Resistance',
  'cubic gate': 'Carnelian Cube',
  'decanter of endless water': 'Decanter of Unending Water',
  'dragon\'s teeth': 'Dragon\'s Teeth',
  'drums of panic': 'Drums of Doom',
  'dust of appearance': 'Dust of Appearing',
  'dust of disappearance': 'Dust of Vanishing',
  'dust of illusion': 'Dust of Seeming',
  'efficient quiver': 'Efficient Quiver',
  'efreeti bottle': 'Magic Lamp',
  'elemental gem': 'Gem of Elemental Conjuring',
  'eversmoking bottle': 'Eversmoking Lamp',
  'eyes of doom': 'Lenses of Doom',
  'eyes of the eagle': 'Eagle Eyes',
  'feather token': 'Feathers of Power',
  'figurines of wondrous power': 'Figurines of Animal Awakening',
  'fruit of the lotus tree': 'Fruit of the Lotus Tree',
  'gauntlets of ogre power': 'Gauntlets of Ogrish Might',
  'gem of brightness': 'Gem of Light',
  'gem of seeing': 'Gem of Truth',
  'gloves of dexterity': 'Gloves of Dexterity',
  'gloves of swimming and climbing': 'Gloves of the Wildman',
  'handy haversack': 'Dimensional Backpack',
  'harp of charming': 'Harp of Ensorcellment',
  'hat of disguise': 'Hat of False Appearance',
  'helm of brilliance': 'Helm of Glimmering',
  'helm of comprehend languages and read magic': 'Helm of Comprehension',
  'helm of telepathy': 'Helm of Thoughts',
  'helm of teleportation': 'Helm of Teleporting',
  'helm of underwater action': 'Helm of the Diver',
  'horn of blasting': 'Trumpet of Blasting',
  'horn of fog': 'Horn of Mist',
  'horn of goodness/evil': 'Trumpet of Good and Evil',
  'horn of the merfolk': 'Horn of the Merfolk',
  'horn of valhalla': 'Horn of Valhalla',
  'horseshoes of speed': 'Horseshoes of Swiftness',
  'horseshoes of the zephyr': 'Horseshoes of the Windrunner',
  'instant fortress': 'Instant Fortress',
  'ioun stones': 'Ioun Stones',
  'iron bands of binding': 'Iron Bands of Binding',
  'iron flask': 'Iron Phial',
  'lady of the lake\'s gift': 'Lady of the Lake\'s Gift',
  'lyre of building': 'Lyre of Creation',
  'mantle of babr-e bayan': 'Mantle of Babr-E Bayan',
  'mantle of spell resistance': 'Mantle of Superior Spell Resistance',
  'manual of bodily health': 'Manual of Bodily Wellness',
  'manual of gainful exercise': 'Manual of Gainful Strength',
  'manual of quickness of action': 'Manual of Dexterous Action',
  'mattock of the titans': 'Mattock of the Ancient Ones',
  'maul of the titans': 'Maul of the Ancient Ones',
  'mead of stuttungr': 'Mead of Stuttungr',
  'medallion of thoughts': 'Medallion of ESP',
  'mirror of life trapping': 'Mirror of Soul Trapping',
  'mirror of mental prowess': 'Mirror of Revealing',
  'mirror of opposition': 'Mirror of Dark Reflection',
  'necklace of adaptation': 'Necklace of Fresh Air',
  'necklace of fireballs': 'Necklace of Fiery Beads',
  'orb of storms': 'Orb of Atmospheric Control',
  'pearl of power': 'Pearl of Recall',
  'pearl of the sirines': 'Pearl of the Sea Kings',
  'periapt of health': 'Jewel of Health',
  'periapt of proof against poison': 'Jewel of Proof Against Poison',
  'periapt of wisdom': 'Jewel of Wisdom',
  'periapt of wound closure': 'Jewel of Healing',
  'phylactery of faithfulness': 'Phylactery of the Devout',
  'phylactery of undead turning': 'Phylactery of Turning',
  'pipes of the sewers': 'Piper\'s Pipes',
  'portable hole': 'Portable Hole',
  'restorative ointment': 'Restorative Salve',
  'ring gates': 'Transporter Gates',
  'robe of the archmagi': 'Robe of the High Magus',
  'robe of blending': 'Robe of Camouflage',
  'robe of eyes': 'Robe of Oculos',
  'robe of scintillating colors': 'Robe of Many Colors',
  'robe of useful items': 'Robe of Many Items',
  'rope of climbing': 'Rogue\'s Rope',
  'rope of entanglement': 'Rope of Entanglement',
  'scabbard of sharpness': 'Scabbard of Keen Edges',
  'scarab of protection': 'Scarab of Protection',
  'seven-league boots': 'Seven-League boots',
  'shrouds of disintegration': 'Cerements of Disintegration',
  'slippers of spider climbing': 'Slippers of Spider Walking',
  'stone of alarm': 'Cube of Alarm',
  'stone of controlling earth elementals': 'Stone of Elemental Earth Command',
  'stone of good luck': 'Stone of Good Fortune',
  'luckstone': 'Stone of Good Fortune',
  'stone horse': 'Stone Horse',
  'strand of prayer beads': 'String of Prayer Beads',
  'thunderstones': 'Greatstones',
  'tome of clear thought': 'Tome of Superior Intellect',
  'tome of leadership and influence': 'Tome of Magnetic Charisma',
  'tome of raudskinna': 'Tome of Raudskinna',
  'tome of understanding': 'Tome of Sagacious Wisdom',
  'well of many worlds': 'Portable Portal',
  'wind fan': 'Wind-Master\'s Fan',
  'wings of flying': 'Wings of Flight',
  'yata-no kagami': 'Yata-No Kagami',
  
  // Rings
  'ring of animal friendship': 'Ring of Animal Loyalty',
  'ring of blinking': 'Blinking Band',
  'ring of chameleon power': 'Ring of Disguise',
  'ring of climbing': 'Ring of the Climber',
  'ring of counterspells': 'Ring of Spell Negation',
  'ring of detect alignment': 'Ring of Detect Disposition',
  'ring of djinni calling': 'Ring of the Djinni Master',
  'ring of elemental command': 'Ring of Elemental Command',
  'ring of energy resistance': 'Ring of Resistance',
  'ring of enfeeblement': 'Ring of Weakening',
  'ring of evasion': 'Ring of Dodging',
  'ring of feather falling': 'Ring of Feather-Lightness',
  'ring of flying': 'Ring of Flying',
  'ring of force shield': 'Ring of Spectral Shielding',
  'ring of freedom of movement': 'Ring of Free Motion',
  'ring of friend shield': 'Ring of Friend Shielding',
  'gyges ring': 'Gyges Ring',
  'ring of invisibility': 'Ring of Invisibility',
  'ring of jumping': 'Ring of Mighty Leaping',
  'lancelot\'s ring': 'Lancelot\'s Ring',
  'ring of mind shielding': 'Ring of Opaque Thought',
  'ring of protection': 'Ring of Armor',
  'ring of the ram': 'Ring of Ramming',
  'ring of regeneration': 'Ring of Regeneration',
  'ring of shooting stars': 'Ring of Starlight',
  'ring of spell storing': 'Ring of Spell Keeping',
  'ring of spell turning': 'Ring of Spell Deflection',
  'ring of sustenance': 'Ring of Nourishment',
  'ring of swimming': 'Ring of Swimming',
  'ring of telekinesis': 'Ring of Telekinetic Power',
  'ring of three wishes': 'Ring of Granting',
  'ring of water walking': 'Ring of Water Striding',
  'ring of wizardry': 'Ring of Eldritch Wizardry',
  'ring of x-ray vision': 'Ring of X-Ray Vision',
  
  // Rods & Staves
  'rod of absorption': 'Rod of Spell Stealing',
  'rod of cancellation': 'Rod of Disenchantment',
  'rod of lordly might': 'Rod of Supreme Usefulness',
  'rod of negation': 'Rod of Deactivation',
  'rod of the python': 'Rod of the Serpent',
  'rod of rulership': 'Rod of Regality',
  'rod of thunder and lightning': 'Rod of Thunderstorms',
  'rod of withering': 'Rod of Atrophy',
  'rod of wonder': 'Rod of Chaos',
  'staff of abjuration': 'Staff of Abjuration',
  'staff of charming': 'Staff of Charm',
  'staff of conjuration': 'Staff of Conjuration',
  'staff of evocation': 'Staff of Evocation',
  'staff of fire': 'Staff of Pyromancy',
  'staff of frost': 'Staff of the Winter Dark',
  'staff of healing': 'Staff of Healing',
  'staff of power': 'Staff of Power',
  'staff of resurrection': 'Staff of Resurrection',
  'staff of striking': 'Staff of Striking Blows',
  'staff of the woodlands': 'Staff of the Druids',
  'wand of illusion': 'Wand of Illusion',
  
  // Cursed Items
  'amulet of inescapable location': 'Amulet of Inescapable Observation',
  'armor of rage': 'Armor of Hate',
  'bag of devouring': 'Devouring Dimensional Pouch',
  'boots of dancing': 'Boots of Uncontrollable Dance',
  'bracers of defenselessness': 'Bracers of Vulnerability',
  'flask of curses': 'Bottle of Doom',
  'gauntlets of fumbling': 'Gauntlets of Clumsiness',
  'helm of opposite aligmnent': 'Helmet of Opposite Disposition',
  'incense of obsession': 'Incense of Magical Obsession',
  'mace of blood': 'Mace of Gore',
  'medallion of thought projection': 'Medallion of the Open Mind',
  'necklace of strangulation': 'Necklace of Asphyxiation',
  'net of snaring': 'Net of Return',
  'periapt of foul rotting': 'Jewel of Foul Rotting',
  'potion of poison': 'Potion of Poison',
  'robe of powerlessness': 'Robe of Enfeeblement',
  'robe of vermin': 'Robe of Insects',
  'ring of clumsiness': 'Ring of Fumbling',
  'scarab of death': 'Scarab of Burrowing',
  'spear, cursed backbiter': 'Spear, Backbiting',
  'stone of weight': 'Stone of Burden',
  'loadstone': 'Stone of Burden',
  'sword, cursed': 'Sword, Cursed',
  'sword, berserking': 'Sword, Berserking',
  'vacuous grimoire': 'Vacuous Tome',
  'zane\'s ire': 'Zane\'s Ire',
  
  // Legendary & Unique Items
  'aegis': 'Aegis',
  'andvaranaut': 'Andvaranaut',
  'angurvadal': 'Angurvadal',
  'book of infinite spells': 'Infinite Spellbook',
  'caduceus': 'Caduceus',
  'carnwennan': 'Carnwennan',
  'chentu': 'Chentu',
  'the cowl of the black fox': 'The Cowl of the Black Fox',
  'deck of many things': 'Deck of Many Things',
  'excalibur': 'Excalibur',
  'the fail-not bow of tristan': 'The Fail-Not Bow of Tristan',
  'hammer of thunderbolts': 'Hammer of Thunderbolts',
  'the hand of glory': 'The Hand Which Knocks',
  'jarrod\'s blade': 'Jarrod\'s Blade',
  'kladenets': 'Kladenets',
  'the lantern of diogenes': 'The Lantern of Diogenes',
  'the mace of the dove': 'The Mace of the Dove',
  'the mantle of lorenzo': 'The Mantle of Lorenzo',
  'mjolnir': 'Mjolnir',
  'moaning diamond': 'Diamond of Grouzal',
  'the orbs of dragonkind': 'Orbs of the Dragon',
  'philosopher\'s stone': 'Philosopher\'s Stone',
  'the ruyi jingu bang': 'The Ruyi Jingu Bang',
  'the saint\'s mace': 'The Saint\'s Mace',
  'the shadowstaff': 'Darkenstaff',
  'sharanga': 'Sharanga',
  'shaield of maccabee': 'Shield of Maccabee',
  'the shield of the sun': 'The Shield of Solar Incandescence',
  'sphere of annihiliation': 'Sphere of Obliteration',
  'staff of the magi': 'Staff of the Magus',
  'the sword of conaire mor': 'The Sword of Conaire Mor',
  'the sword of peleus': 'The Sword of Peleus',
  'talisman of pure good': 'Talisman of Unwavering Good',
  'talisman of the sphere': 'Talisman of the Obliterator',
  'talisman of ultimate evil': 'Talisman of Unyielding Evil',
  'tarnhelm': 'Tarnhelm',
  'tome of the unclean': 'Tome of the Unclean',
  'tyrfing': 'Tyrfing',
  'uchide no kozuchi': 'Uchide No Kozuchi',
  'varunastra': 'Varunastra',
  'amulet of proof against detection and location': 'Amulet of Warding Against Detection',
  'incense of meditation': 'Incense of Tranquility',
  'boots of climbing': 'Rogue\'s Boots',
  'bracers of defense': 'Magic Bracers',
  'cloak of protection': 'Cloak of Armor',
  'buckler of defense': 'Buckler of Defense',
  'flametongue': 'Flametongue',
  'hag eye': 'Hag\'s Eye',
  
  // Generic protection items for consistent naming
  'robe of protection': 'robe of armor',
  'pectoral of protection': 'pectoral of armor'
};

// Magic item mechanical explanations
// NO MAGIC ITEM CAN BE PRINTED WITHOUT SOME DEGREE OF MECHANICAL EXPLANATION
export const MAGIC_ITEM_MECHANICS: Record<string, string> = {
  // Armor Items
  'robe of armor': 'AC +1 to +5',
  'ring of armor': 'AC +1 to +5',
  'pectoral of armor': 'AC +1 to +3',
  'bracers of defense': 'AC +1 to +8',
  'cloak of protection': 'AC +1 to +5, saves +1 to +5',
  'shield': 'AC +1 to +5',
  'medium steel shield': 'AC +1',

  // Weapons
  'dagger of envenomation': 'save vs. poison or die',
  'sword of sharpness': '+1 to +5, severs limbs on natural 20',
  'frost brand': '+3 vs. fire creatures, immunity to fire',
  'flame tongue': '+1 to +5, +2d6 fire damage',
  'holy avenger': '+5 vs. evil, spell resistance',
  'vorpal blade': 'severs head on natural 20',

  // Potions
  'potion of healing': 'heals 1d8+1 HP',
  'potion of extra healing': 'heals 2d8+2 HP',
  'potion of heroism': '+2 to attacks, saves, and damage for 1 hour',
  'potion of giant strength': 'strength 18/00 for 1 hour',
  'potion of invisibility': 'invisible for 1 hour or until attacking',

  // Rings
  'ring of regeneration': 'regains 1 HP per round',
  'ring of spell storing': 'stores 1-5 spell levels',
  'ring of wizardry': 'doubles 1st-3rd level spells',
  'ring of telekinesis': 'telekinesis at will',
  'ring of invisibility': 'invisible at will',

  // Wands and Staves
  'wand of fireballs': '6d6 damage, 20 charges',
  'wand of lightning bolts': '6d6 damage, 20 charges',
  'staff of power': 'various spells, 50 charges',
  'staff of the magi': 'powerful spells, 50 charges',

  // Miscellaneous
  'bag of holding': 'holds 10,000 coins weight',
  'boots of speed': 'double movement rate',
  'gauntlets of ogre power': 'strength 18/00',
  'helm of telepathy': 'ESP and suggestion',
  'amulet of life protection': 'prevents level drain',
  'crystal ball': 'scrying device',
  'deck of many things': 'random magical effects',
  'portable hole': 'extradimensional space',

  // Standard bonuses (catch-all for +X items)
  '+1': '+1 bonus',
  '+2': '+2 bonus',
  '+3': '+3 bonus',
  '+4': '+4 bonus',
  '+5': '+5 bonus',
};

// Function to detect if an item is magical
export function isMagicalItem(item: string): boolean {
  const magicIndicators = [
    /\+\d+/,                                    // Has bonus like +1, +2, etc.
    /\bof\s+\w+/i,                             // "of something" format
    /\b(ring|wand|staff|rod|potion|scroll)\b/i, // Common magic item types
    /\b(magic|magical|enchanted)\b/i,          // Explicit magic words
    /\b(holy|unholy|blessed|cursed)\b/i,       // Religious items
  ];

  return magicIndicators.some(pattern => pattern.test(item));
}

// Function to add mechanical explanations to magic items
export function addMagicItemMechanics(item: string): string {
  if (!isMagicalItem(item)) {
    return item;
  }

  // Check for exact matches first - use em dashes to avoid nested parentheses
  const lowerItem = item.toLowerCase().trim();
  if (MAGIC_ITEM_MECHANICS[lowerItem]) {
    return `${item}—${MAGIC_ITEM_MECHANICS[lowerItem]}`;
  }

  // Check for partial matches BEFORE generic +X bonus fallback
  // This ensures "pectoral of armor +3" matches "pectoral of armor" not just "+3"
  const bonusMatch = item.match(/\+(\d+)/);
  for (const [itemName, mechanics] of Object.entries(MAGIC_ITEM_MECHANICS)) {
    // Skip pure bonus entries like "+1", "+2" for now
    if (itemName.startsWith('+')) {
      continue;
    }
    if (lowerItem.includes(itemName.toLowerCase())) {
      // Skip generic "shield" match if this is a specific shield with a bonus
      if (itemName === 'shield' && bonusMatch) {
        continue;
      }
      return `${item}—${mechanics}`;
    }
  }

  // Handle generic +X bonuses as fallback
  if (bonusMatch) {
    const bonus = bonusMatch[1];
    if (MAGIC_ITEM_MECHANICS[`+${bonus}`]) {
      return `${item}—${MAGIC_ITEM_MECHANICS[`+${bonus}`]}`;
    }
  }

  // If no specific mechanics found, add generic explanation
  return `${item}—see Appendix: Magic Items`;
}

// Helper function to apply all name mappings
export function applyNameMappings(text: string): string {
  let result = text;

  // Apply spell mappings
  for (const [oldName, newName] of Object.entries(SPELL_NAME_MAPPINGS)) {
    const regex = new RegExp(`\\b${oldName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi');
    result = result.replace(regex, newName);
  }

  // Apply monster mappings
  for (const [oldName, newName] of Object.entries(MONSTER_NAME_MAPPINGS)) {
    const regex = new RegExp(`\\b${oldName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi');
    result = result.replace(regex, newName);
  }

  // Apply magic item mappings
  for (const [oldName, newName] of Object.entries(MAGIC_ITEM_MAPPINGS)) {
    const regex = new RegExp(`\\b${oldName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi');
    result = result.replace(regex, newName);
  }

  return result;
}
