import fs from 'fs';
import path from 'path';
import { analyzeFullDocument } from '@/lib/full-document-pipeline';

async function main() {
  const cwd = process.cwd();
  const samplePath = path.join(cwd, 'system-profiles', 'Pathfinder2', 'sample_stat_blocks.md');

  if (!fs.existsSync(samplePath)) {
    console.error('PF2e sample file not found:', samplePath);
    process.exit(2);
  }

  let md = fs.readFileSync(samplePath, 'utf8');
  // Convert PF2e-style H2 entries (## Title) into numbered bestiary-style
  // headers to make them compatible with the existing extractor which
  // expects '### <n>. Name' headers.
  const h2Matches = md.match(/^##\s+.+$/gim) || [];
  if (h2Matches.length > 0) {
    let counter = 1;
    md = md.replace(/^##\s+(.+)$/gim, () => {
      const header = `### ${counter}. ${RegExp.$1.trim()}`;
      counter += 1;
      return header;
    });
  }
  console.log('Analyzing PF2e sample stat blocks...');

  const analysis = analyzeFullDocument(md, 'Pathfinder2 sample', 'enhanced');

  const destDir = path.join(cwd, 'src', 'components', 'mocks');
  if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
  const dest = path.join(destDir, 'pf2e-sample.mock.ts');
  const content = `/* This file is auto-generated by scripts/generate-pf2e-mock.ts */\nexport const pf2eSampleAnalysis = ${JSON.stringify(analysis, null, 2)} as const;\n`;

  fs.writeFileSync(dest, content, 'utf8');

  console.log('Wrote PF2e mock to', dest);
}

main().catch((err) => {
  console.error('Error generating PF2e mock:', err);
  process.exit(1);
});
