import fs from 'fs';
import path from 'path';
import { analyzeFullDocument } from '@/lib/full-document-pipeline';

async function main() {
  const cwd = process.cwd();
  // Try to find the mouths-of-madness canonical file in 'CnC Docs' folder
  const docsDirCandidates = [path.join(cwd, 'CnC Docs'), path.join(cwd, 'CnC-Docs'), path.join(cwd, 'CnC Docs/')];
  let filePath = '';
  for (const dir of docsDirCandidates) {
    if (!fs.existsSync(dir)) continue;
    const files = fs.readdirSync(dir);
    const candidate = files.find(f => f.startsWith('mouths-of-madness-canonical'));
    if (candidate) {
      filePath = path.join(dir, candidate);
      break;
    }
  }
  if (!fs.existsSync(filePath)) {
    filePath = path.join(cwd, 'CnC Docs', 'mouths-of-madness-canonical-clean.md');
  }

  if (!fs.existsSync(filePath)) {
    console.error('Cannot find mouths-of-madness-canonical*.md in CnC Docs. Abort.');
    process.exit(2);
  }

  const md = fs.readFileSync(filePath, 'utf8');

  console.log('Running full-document pipeline on:', filePath);
  const analysis = analyzeFullDocument(md, 'Mouths of Madness', 'enhanced');
  
  // If we have classification results, merge them into the analysis for Storybook use
  const classificationPath = path.join(process.cwd(), 'data', 'mouths-of-madness', 'creature-classifications.json');
  if (fs.existsSync(classificationPath)) {
    try {
      const classifications = JSON.parse(fs.readFileSync(classificationPath, 'utf8'));
      if (Array.isArray(classifications) && analysis.creatures) {
        const byEntry = new Map<number, any>();
        for (const c of classifications) {
          if (typeof c.entryNumber === 'number') byEntry.set(c.entryNumber, c);
        }

        for (const creature of analysis.creatures) {
          const c = byEntry.get(creature.entryNumber);
          if (c) {
            creature.classification = {
              type: c.type,
              subtype: c.subtype,
              confidence: c.confidence,
              reasoning: c.reasoning,
              warnings: c.warnings,
            } as any;
          } else {
            creature.classification = null;
          }
        }
      }
    } catch (err) {
      console.warn('Failed to attach classification data to Storybook mock', err);
    }
  }

  // Sanitize the object: remove circular or complex data if needed
  const out = JSON.stringify(analysis, null, 2);

  const destDir = path.join(cwd, 'src', 'components', 'mocks');
  if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
  const dest = path.join(destDir, 'mouths-of-madness.mock.ts');

  const content = `/* This file is auto-generated by scripts/generate-mouths-mock.ts */\nexport const mouthsOfMadnessAnalysis = ${out} as const;\n`;
  fs.writeFileSync(dest, content, 'utf8');

  console.log('Wrote mock to', dest);
}

main().catch((err) => {
  console.error('Error generating mock:', err);
  process.exit(1);
});
