import fs from 'fs';
import path from 'path';
import { analyzeFullDocument } from '@/lib/full-document-pipeline';

async function main() {
  const cwd = process.cwd();
  const src = path.join(cwd, 'CnC Docs', 'Essential Places 10.30.25_headers_export.md');
  if (!fs.existsSync(src)) {
    console.error('Source markdown missing:', src);
    process.exit(2);
  }

  const md = fs.readFileSync(src, 'utf8');
  console.log('Running full-document pipeline on:', src);

  const analysis = analyzeFullDocument(md, 'Essential Places (headers export)', 'enhanced');

  // Sanitize the object to avoid circular references and keep config small
  const out = JSON.stringify(analysis, null, 2);

  const destDir = path.join(cwd, 'src', 'components', 'mocks');
  if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
  const dest = path.join(destDir, 'essential-places.mock.ts');

  const content = `/* This file is auto-generated by scripts/generate-essentialplaces-mock.ts */\nexport const essentialPlacesAnalysis = ${out} as const;\n`;
  fs.writeFileSync(dest, content, 'utf8');

  console.log('Wrote mock to', dest);
}

main().catch(err => {
  console.error('Error generating mock:', err);
  process.exit(1);
});
