/* This file is auto-generated by scripts/generate-pf2e-mock.ts */
export const pf2eSampleAnalysis = {
  "creatures": [
    {
      "name": "### 1. Pit Trap (Hazard)",
      "original": "### 1. Pit Trap (Hazard)\nThis block tests standard Monster classification and simple action parsing.",
      "converted": "**### 1. Pit Trap**",
      "validation": {
        "warnings": [
          {
            "type": "error",
            "category": "Disposition",
            "message": "Add a Disposition line using noun-form alignment (e.g., law/good).",
            "suggestion": "Replace \"Alignment\" with \"Disposition\" and use noun forms (law/good, chaos/evil, etc.)."
          },
          {
            "type": "error",
            "category": "Race & Class",
            "message": "Include Race & Class details (e.g., human, 5th level fighter)."
          },
          {
            "type": "warning",
            "category": "Hit Points (HP)",
            "message": "Hit Points (HP) missing. Provide either a total or dice expression."
          },
          {
            "type": "warning",
            "category": "Armor Class (AC)",
            "message": "Armor Class (AC) missing. Include base AC and modifiers when possible."
          },
          {
            "type": "info",
            "category": "Primary attributes",
            "message": "Primary attributes (Prime) help with quick reference."
          },
          {
            "type": "info",
            "category": "Equipment",
            "message": "Listing notable equipment helps with conversion fidelity."
          },
          {
            "type": "warning",
            "category": "Name Formatting",
            "message": "NPC name should be bolded with **double asterisks**.",
            "suggestion": "Wrap the NPC name in **double asterisks** to match the style guide."
          },
          {
            "type": "error",
            "category": "Vital Stats",
            "message": "Vital stats are unavailable. Include either Hit Points (HP) or HD and an Armor Class (AC).",
            "suggestion": "Add Hit Points (HP): <number> or HD: X(dY) and an Armor Class (AC): <value> to the stat block."
          }
        ],
        "complianceScore": 0
      },
      "canonicalData": {
        "name": "### 1. Pit Trap (Hazard)",
        "level": null,
        "hd": null,
        "hp": null,
        "ac": null,
        "disposition": null,
        "primaryAttributes": null,
        "equipment": null,
        "coins": null,
        "notes": [
          "This block tests standard Monster classification and simple action parsing."
        ]
      },
      "entryNumber": 1,
      "creatureType": "Pit Trap",
      "rawMarkdown": "### 1. Pit Trap (Hazard)\nThis block tests standard Monster classification and simple action parsing.\n\n**Level:** 1\n**Type:** Small humanoid (goblin)\n**Alignment:** Chaotic Evil\n**Traits:** Goblin, Humanoid, Orcish (trait to test)\n\n**AC:** 16 (Leather Armor)\n**HP:** 20\n**Speed:** 25 feet\n**Perception:** +5\n**Saves:** Fort +5, Ref +8, Will +2\n**Languages:** Common, Goblin\n\n**Abilities:**\n**Sneak Attack (Trait):** +1d6 precision damage if the target is flat-footed.\n**Maneuver (Action):** **Climb:** +8, **Stealth:** +6\n\n**Actions:**\n**Shortsword (Melee, 1 Action):** +8 to hit, 1d6+3 slashing damage.\n**Shortbow (Ranged, 1 Action):** +8 to hit, 1d6 piercing damage (Range 60 ft.).\n---"
    },
    {
      "name": "### 2. Pit Trap (Hazard)",
      "original": "### 2. Pit Trap (Hazard)\nThis block tests named NPC status, multiple defensive actions, and complex ability score structure. Your PF2e parser adaptation must classify this as an **NPC**.",
      "converted": "**### 2. Pit Trap**",
      "validation": {
        "warnings": [
          {
            "type": "error",
            "category": "Disposition",
            "message": "Add a Disposition line using noun-form alignment (e.g., law/good).",
            "suggestion": "Replace \"Alignment\" with \"Disposition\" and use noun forms (law/good, chaos/evil, etc.)."
          },
          {
            "type": "error",
            "category": "Race & Class",
            "message": "Include Race & Class details (e.g., human, 5th level fighter)."
          },
          {
            "type": "warning",
            "category": "Hit Points (HP)",
            "message": "Hit Points (HP) missing. Provide either a total or dice expression."
          },
          {
            "type": "warning",
            "category": "Armor Class (AC)",
            "message": "Armor Class (AC) missing. Include base AC and modifiers when possible."
          },
          {
            "type": "info",
            "category": "Primary attributes",
            "message": "Primary attributes (Prime) help with quick reference."
          },
          {
            "type": "info",
            "category": "Equipment",
            "message": "Listing notable equipment helps with conversion fidelity."
          },
          {
            "type": "warning",
            "category": "Name Formatting",
            "message": "NPC name should be bolded with **double asterisks**.",
            "suggestion": "Wrap the NPC name in **double asterisks** to match the style guide."
          },
          {
            "type": "error",
            "category": "Vital Stats",
            "message": "Vital stats are unavailable. Include either Hit Points (HP) or HD and an Armor Class (AC).",
            "suggestion": "Add Hit Points (HP): <number> or HD: X(dY) and an Armor Class (AC): <value> to the stat block."
          }
        ],
        "complianceScore": 0
      },
      "canonicalData": {
        "name": "### 2. Pit Trap (Hazard)",
        "level": null,
        "hd": null,
        "hp": null,
        "ac": null,
        "disposition": null,
        "primaryAttributes": null,
        "equipment": null,
        "coins": null,
        "notes": [
          "This block tests named NPC status, multiple defensive actions, and complex ability score structure. Your PF2e parser adaptation must classify this as an **NPC**."
        ]
      },
      "entryNumber": 2,
      "creatureType": "Pit Trap",
      "rawMarkdown": "### 2. Pit Trap (Hazard)\nThis block tests named NPC status, multiple defensive actions, and complex ability score structure. Your PF2e parser adaptation must classify this as an **NPC**.\n\n**Level:** 8\n**Type:** Medium Humanoid (human)\n**Alignment:** Lawful Good\n**Traits:** Human, Leader, Classed (trait to test parser logic)\n\n**AC:** 27 (Plate Armor)\n**HP:** 140\n**Speed:** 20 feet\n**Perception:** +17\n**Saves:** Fort +16, Ref +13, Will +19\n\n**Ability Scores:** STR 18 (+4), DEX 14 (+2), CON 18 (+4), INT 10 (+0), WIS 20 (+5), CHA 16 (+3)\n\n**Gear:**\n**Weapon:** +1 Flaming Longsword (Melee, 1 Action)\n**Armor:** +1 Full Plate (Worn)\n**Coin:** 50 gold in coin, 15 silver in coin\n\n**Abilities:**\n**Marshal's Aura (Aura, 10 ft.):** Allies gain +1 status bonus to saving throws.\n**Challenge (Action):** Marks one enemy for defeat, granting a +2 status bonus to attack rolls against it.\n\n**Actions:**\n**Longsword Strike (1 Action):** +18 to hit (includes marshal aura), 2d8+8 slashing damage + 1d6 fire damage.\n**Battle Cry (1 Action, Incapacitation):** All enemies within 30 feet must attempt a DC 24 Will save or become frightened 1.\n---"
    },
    {
      "name": "### 3. Pit Trap (Hazard)",
      "original": "### 3. Pit Trap (Hazard)\nThis block tests the ability to parse a non-creature entity type, which requires different field validation.",
      "converted": "**### 3. Pit Trap**",
      "validation": {
        "warnings": [
          {
            "type": "error",
            "category": "Disposition",
            "message": "Add a Disposition line using noun-form alignment (e.g., law/good).",
            "suggestion": "Replace \"Alignment\" with \"Disposition\" and use noun forms (law/good, chaos/evil, etc.)."
          },
          {
            "type": "error",
            "category": "Race & Class",
            "message": "Include Race & Class details (e.g., human, 5th level fighter)."
          },
          {
            "type": "warning",
            "category": "Hit Points (HP)",
            "message": "Hit Points (HP) missing. Provide either a total or dice expression."
          },
          {
            "type": "warning",
            "category": "Armor Class (AC)",
            "message": "Armor Class (AC) missing. Include base AC and modifiers when possible."
          },
          {
            "type": "info",
            "category": "Primary attributes",
            "message": "Primary attributes (Prime) help with quick reference."
          },
          {
            "type": "info",
            "category": "Equipment",
            "message": "Listing notable equipment helps with conversion fidelity."
          },
          {
            "type": "warning",
            "category": "Name Formatting",
            "message": "NPC name should be bolded with **double asterisks**.",
            "suggestion": "Wrap the NPC name in **double asterisks** to match the style guide."
          },
          {
            "type": "error",
            "category": "Vital Stats",
            "message": "Vital stats are unavailable. Include either Hit Points (HP) or HD and an Armor Class (AC).",
            "suggestion": "Add Hit Points (HP): <number> or HD: X(dY) and an Armor Class (AC): <value> to the stat block."
          }
        ],
        "complianceScore": 0
      },
      "canonicalData": {
        "name": "### 3. Pit Trap (Hazard)",
        "level": null,
        "hd": null,
        "hp": null,
        "ac": null,
        "disposition": null,
        "primaryAttributes": null,
        "equipment": null,
        "coins": null,
        "notes": [
          "This block tests the ability to parse a non-creature entity type, which requires different field validation."
        ]
      },
      "entryNumber": 3,
      "creatureType": "Pit Trap",
      "rawMarkdown": "### 3. Pit Trap (Hazard)\nThis block tests the ability to parse a non-creature entity type, which requires different field validation.\n\n**Level:** 3\n**Type:** Mechanical, Trap\n**Stealth:** DC 23 (Expert)\n**Disable:** DC 20 (Expert)\n**Immunity:** Critical Hits, Object Immunities\n\n**AC:** 18\n**Hardness:** 8\n**HP:** 32 (Broken Threshold 16)\n\n**Effect (Trigger):** Pressure plate is stepped on.\n**Effect (Ransom):** Target falls 20 feet, taking 2d6 falling damage and 4d6 piercing damage from spikes (DC 20 Basic Reflex Save). Target is Immobilized."
    }
  ],
  "stats": {
    "totalCreatures": 3,
    "creatureTypeFrequency": {},
    "dispositionFrequency": {},
    "acRange": {
      "min": 0,
      "max": 0,
      "mean": 0,
      "median": 0
    },
    "hpRange": {
      "min": 0,
      "max": 0,
      "mean": 0,
      "median": 0
    },
    "equipmentFrequency": {},
    "spellFrequency": {},
    "encounterBalance": {
      "totalEstimatedXP": 300,
      "avgCREstimate": 1
    }
  },
  "validationReport": {
    "totalValidationScore": 0,
    "perCreatureScores": [
      0,
      0,
      0
    ],
    "crossEntryIssues": [],
    "statisticalAnomalies": [],
    "recommendations": [
      "Overall compliance is below 70% - consider using auto-correction features",
      "9 critical errors detected - review these before publication"
    ],
    "totalIssues": 24,
    "criticalIssues": 9
  },
  "metadata": {
    "documentName": "Pathfinder2 sample",
    "totalEntries": 3,
    "processingDate": "2025-11-19T21:12:04.276Z",
    "successRate": 100
  }
} as const;
